import esbuild from "esbuild";
import process from "process";
import module from "module";
import fs from "fs";
import path from "path";
import * as sass from "sass";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Obsidian Citation Manager Plugin
*/
`;

// Simple .env parser to avoid runtime dependencies
function loadEnv() {
  const envPath = path.resolve(".env");
  if (fs.existsSync(envPath)) {
    const lines = fs.readFileSync(envPath, "utf8").split(/\r?\n/);
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith("#")) {
        const idx = trimmed.indexOf("=");
        if (idx !== -1) {
          const key = trimmed.slice(0, idx).trim();
          const val = trimmed.slice(idx + 1).trim();
          if (!process.env[key]) {
            process.env[key] = val;
          }
        }
      }
    }
  }
}

loadEnv();

const prod = process.argv[2] === "production";
const builtins = module.builtinModules;
const VAULT_PLUGIN_DIR = process.env.OBSIDIAN_VAULT_DIR || process.env.VAULT_PLUGIN_DIR || null;

function ensureDistDir() {
  const distDir = path.resolve("dist");
  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }
}

function buildStyles() {
  try {
    ensureDistDir();
    const scssPath = path.resolve("src/frontend/styles/main.scss");
    const outCssPublic = path.resolve("public/styles.css");
    const outCssDist = path.resolve("dist/styles.css");
    if (fs.existsSync(scssPath)) {
      const res = sass.compile(scssPath, { sourceMap: false });
      fs.writeFileSync(outCssPublic, res.css);
      fs.writeFileSync(outCssDist, res.css);
      console.log("[Style Build] Compiled modular SCSS -> public/styles.css and dist/styles.css");
    }
  } catch (err) {
    console.error("[Style Build] SCSS compilation error:", err);
  }
}

function syncDistAssets() {
  ensureDistDir();
  const manifestSrc = path.resolve("public/manifest.json");
  const manifestDest = path.resolve("dist/manifest.json");
  if (fs.existsSync(manifestSrc)) {
    fs.copyFileSync(manifestSrc, manifestDest);
  }
}

function copyToVault() {
  if (!VAULT_PLUGIN_DIR) return;
  try {
    const parentDir = path.dirname(VAULT_PLUGIN_DIR);
    if (fs.existsSync(parentDir)) {
      if (!fs.existsSync(VAULT_PLUGIN_DIR)) {
        fs.mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
      }
      const files = [
        { src: "dist/main.js", dest: "main.js" },
        { src: "dist/manifest.json", dest: "manifest.json" },
        { src: "dist/styles.css", dest: "styles.css" },
      ];
      for (const item of files) {
        if (fs.existsSync(item.src)) {
          fs.copyFileSync(item.src, path.join(VAULT_PLUGIN_DIR, item.dest));
        }
      }
      console.log(`[Plugin Build] Copied release files to vault plugin directory: ${VAULT_PLUGIN_DIR}`);
    }
  } catch (err) {
    console.warn(`[Plugin Build] Warning copying to vault: ${err.message}`);
  }
}

buildStyles();
syncDistAssets();

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "dist/main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  syncDistAssets();
  copyToVault();
  process.exit(0);
} else {
  await context.watch();
}
