import esbuild from "esbuild";
import process from "process";
import module from "module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Obsidian Citation Manager & Reference Studio
*/
`;

const prod = process.argv[2] === "production";
const builtins = module.builtinModules;
const VAULT_PLUGIN_DIR = process.env.OBSIDIAN_VAULT_DIR || process.env.VAULT_PLUGIN_DIR || null;

function copyToVault() {
  if (!VAULT_PLUGIN_DIR) return;
  try {
    const parentDir = path.dirname(VAULT_PLUGIN_DIR);
    if (fs.existsSync(parentDir)) {
      if (!fs.existsSync(VAULT_PLUGIN_DIR)) {
        fs.mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
      }
      const files = [
        { src: "main.js", dest: "main.js" },
        { src: "public/manifest.json", dest: "manifest.json" },
        { src: "public/styles.css", dest: "styles.css" },
      ];
      for (const item of files) {
        if (fs.existsSync(item.src)) {
          fs.copyFileSync(item.src, path.join(VAULT_PLUGIN_DIR, item.dest));
        }
      }
      console.log(`[Plugin Build] Copied release files to vault plugin directory: ${VAULT_PLUGIN_DIR}`);
    }
  } catch (err) {
    console.warn(`[Plugin Build] Warning copying to vault: ${err.message}`);
  }
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  copyToVault();
  process.exit(0);
} else {
  await context.watch();
}
